FROM maven:3-jdk-8-alpine as dev
COPY ./ ./
RUN mvn clean package -DskipTests

FROM fabric8/java-alpine-openjdk8-jdk
LABEL maintainer nicopaez@computer.org
WORKDIR /deployments
COPY --from=dev target/passwordapi-*.jar ./app.jar
EXPOSE 8080
USER 405